version: '3.6'

services:
  db:
    image: postgres
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/apacheparser
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  pgdata: