# Generated by Django 2.1.5 on 2019-01-16 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(db_index=True, max_length=40, validators=[django.core.validators.validate_ipv46_address])),
                ('tms', models.DateTimeField()),
                ('request_method', models.TextField(max_length=5)),
                ('request_uri', models.TextField()),
                ('request_code', models.IntegerField()),
                ('request_size', models.IntegerField()),
            ],
        ),
        migrations.AddIndex(
            model_name='logs',
            index=models.Index(fields=['request_method'], name='apache_view_request_379766_idx'),
        ),
        migrations.AddIndex(
            model_name='logs',
            index=models.Index(fields=['request_uri'], name='apache_view_request_39d32d_idx'),
        ),
        migrations.AddIndex(
            model_name='logs',
            index=models.Index(fields=['request_code'], name='apache_view_request_f52909_idx'),
        ),
        migrations.AddIndex(
            model_name='logs',
            index=models.Index(fields=['request_size'], name='apache_view_request_d5a051_idx'),
        ),
    ]
