# Generated by Django 2.1.5 on 2019-01-17 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apache_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'verbose_name': 'logs'},
        ),
    ]
